### ISSUE TITLE
FileInsight dowload

### ISSUE THREAD

**Issue by Beercow** [nmantani/FileInsight-plugins#2]
Do you know where to download FileInsight from? Doesn’t seem to be available anymore.

**Comment by nmantani** [comment]
Though FileInsight was removed from [Trellix Free Tools](https://www.trellix.com/en-us/downloads/free-tools.html) website,  [FileInsight installer](https://downloadcenter.trellix.com/products/mcafee-avert/fileinsight.msi) is still available at [https://downloadcenter.trellix.com/products/mcafee-avert/](https://downloadcenter.trellix.com/products/mcafee-avert/). If you install FileInsight-plugins with the installation PowerShell script ([installation instruction](https://github.com/nmantani/FileInsight-plugins#how-to-install)), the script will also install FileInsight.
